#ifndef SDF_DEV_PROTOCOL_H
#define SDF_DEV_PROTOCOL_H

/* Requests queued for the host-file worker. */
#define SDF_DEV_OPERATION_NONE 0
#define SDF_DEV_OPERATION_OPEN_READ 1
#define SDF_DEV_OPERATION_OPEN_WRITE 2
#define SDF_DEV_OPERATION_SEEK 3
#define SDF_DEV_OPERATION_GET_SIZE 4
#define SDF_DEV_OPERATION_READ 5
#define SDF_DEV_OPERATION_WRITE 6
#define SDF_DEV_OPERATION_CLOSE 7
#define SDF_DEV_OPERATION_READ_BUFFER 8
#define SDF_DEV_OPERATION_WRITE_BUFFER 9

/* Worker lifecycle states; 0 and 1 remain unnamed. */
#define SDF_DEV_STATE_OPENING 2
#define SDF_DEV_STATE_SEEKING 3
#define SDF_DEV_STATE_READING 4
#define SDF_DEV_STATE_WRITING 5
#define SDF_DEV_STATE_CLOSING 6
#define SDF_DEV_STATE_ACTIVE 7
#define SDF_DEV_STATE_COMPLETE 8
#define SDF_DEV_STATE_INACTIVE 9

#endif /* SDF_DEV_PROTOCOL_H */
