#!/usr/bin/env python3
"""Analyse the retail ELF with romwright and refresh config/<version>/symbol_addrs.txt.

    python tools/romwright_sync.py [dds1 dds2] [--sigs DIR] [--reimport]

romwright (https://github.com/Raikaru/ventris) discovers function starts from
flow and names library code from signature databases built from SDK archives
you own:

    romwright-cli signatures build --archive libkernl.a --package ps2sdk:libkernl \\
        --license proprietary-local --out sigs/libkernl.db

The project store lives in build/romwright/ (derived, not committed). The
generated block of symbol_addrs.txt sits between the BEGIN/END markers; rows
outside the block are hand-curated and win over generated ones at the same
address.

A signature name is only taken when it lands on exactly one function: a library
routine is linked once, so a name that matches several bodies is a weak pattern
(tiny masked stubs), not evidence.
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VERSIONS = json.loads((ROOT / "config" / "versions.json").read_text())
PROJECT = ROOT / "build" / "romwright"
BEGIN = "// BEGIN romwright (generated by tools/romwright_sync.py; edit outside this block)"
END = "// END romwright"
PLACEHOLDER = re.compile(r"^(FUN|func|sub|entry)_?[0-9a-fA-F]*$")
ROW = re.compile(r"^\s*(\S+)\s*=\s*(0x[0-9A-Fa-f]+)\s*;")


def romwright() -> str:
    exe = os.environ.get("ROMWRIGHT") or shutil.which("romwright-cli")
    if not exe:
        raise SystemExit("romwright-cli not found: put it on PATH or set ROMWRIGHT=/path/to/romwright-cli")
    return exe


def run(*args: str) -> str:
    return subprocess.run([romwright(), *args], check=True, capture_output=True, text=True).stdout


def import_program(version: str, sigs: Path | None, reimport: bool) -> None:
    programs = run("programs", "--project", str(PROJECT)) if (PROJECT / "project.sqlite").exists() else ""
    if not reimport and re.search(rf"\b{version}\b", programs):
        return
    elf = ROOT / "orig" / version / VERSIONS[version]["serial"]
    args = ["import", str(elf), "--name", version, "--project", str(PROJECT)]
    if sigs:
        dbs = sorted(str(p) for p in sigs.glob("*.db") if p.stat().st_size > 16)
        if dbs:
            args += ["--signatures", ",".join(dbs)]
    print(run(*args).strip())


def functions(version: str) -> list[tuple[int, int, str]]:
    out = run("functions", version, "--limit", "1000000", "--project", str(PROJECT))
    rows = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 3 and re.fullmatch(r"[0-9a-f]{8}", parts[0]):
            rows.append((int(parts[0], 16), int(parts[1]), parts[2]))
    return rows


def write_symbols(version: str) -> None:
    rows = functions(version)
    counts = collections.Counter(name for _, _, name in rows)
    config = ROOT / "config" / version
    path = config / "symbol_addrs.txt"
    text = path.read_text() if path.exists() else ""
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1] if END in rest else ""
    else:
        head, tail = text, ""
    curated = {int(m.group(2), 16) for line in (head + tail).splitlines() if (m := ROW.match(line))}
    # False starts (tools/find_fragments.py): pieces of the preceding function.
    fragments = config / "not_functions.txt"
    skip = {int(line.split()[0], 16) for line in fragments.read_text().splitlines()
            if line.strip() and not line.startswith("#")} if fragments.exists() else set()

    generated, named = [], 0
    for addr, size, name in rows:
        if addr in curated or addr in skip:
            continue
        if PLACEHOLDER.match(name) or counts[name] > 1:
            name = f"func_{addr:08X}"
        else:
            named += 1
        # No size: romwright extents are unreliable around switch tables, and a
        # size makes spimdisasm absorb the following functions as alabels.
        generated.append(f"{name} = 0x{addr:08X}; // type:func")
    body = "\n".join([BEGIN, *generated, END])
    path.write_text(head.rstrip("\n") + ("\n" if head.strip() else "") + body + "\n" + tail.lstrip("\n"))
    print(f"{version}: {len(generated)} functions ({named} library names) -> {path.relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("versions", nargs="*", default=list(VERSIONS))
    ap.add_argument("--sigs", type=Path, default=os.environ.get("DDS_SDK_SIGS"),
                    help="directory of romwright signature .db files (env DDS_SDK_SIGS)")
    ap.add_argument("--reimport", action="store_true", help="re-run analysis even if the program exists")
    args = ap.parse_args()
    PROJECT.mkdir(parents=True, exist_ok=True)
    for version in args.versions:
        if version not in VERSIONS:
            ap.error(f"unknown version {version}")
        import_program(version, Path(args.sigs) if args.sigs else None, args.reimport)
        write_symbols(version)


if __name__ == "__main__":
    main()
