typedef struct EffPacketParams {
    s16 parameterCount;
    s16 vertexCount;
    u16 primitive;
    u16 mask;
    u32 color;
    u32 *parameters;
    u128 *positions;
    u128 *normals;
    u32 *texcoords;
    u32 *extraTexcoords;
    u32 *colors;
    void *(*allocate)(s32);
    f32 depth;
} EffPacketParams;

typedef struct SdfTextParam SdfTextParam;
extern u32 D_0034E090[];
extern u32 D_0034E0A0[];
extern SdfPoolNode *D_0034E0B0[];
extern void sdfComposeVuMatrixFromRegisters(void);
extern void sdfConsAppendVuPacket(s32, s32 (*)(s32));
extern void sdfConsAppendAssetPacket(s32, void *, s32 (*)(s32));
extern void sdfAppendPacket(SdfListHead *, u32);
extern f32 sdfEvaluateCosineViaSinePhaseShift(f32);
extern f32 sdfSinPoly(f32);
extern void func_002DA438(SdfTextParam *, u32);
extern void func_002DA5E0(SdfTextParam *, u32);
extern void *func_0015FE20(EffPacketParams *);

void func_001528C0(EffUnitObject *instance) {
    EffPacketParams params;
    s32 modeValues[3];
    f32 matrix[16] __attribute__((aligned(16)));
    f32 positions[4][4] __attribute__((aligned(16)));
    f32 uv[4][2];
    f32 secondaryUv[4][2];
    s32 list;
    BillChildPayload *child;
    SdfTex *texture;
    SdfPoolNode *surface;
    f32 x, y;
    f32 cosine, sine;
    f32 width, height;

    if (!billGetKindOneParameter((BillObj *)instance->billboard)) {
        return;
    }
    effReadBillboardModeValues(instance, modeValues);
    list = sdfAllocPacketAligned(0x20);
    sdfInitPacketList((SdfListHead *)list);
    VU0_LOAD_MATRIX(instance->matrix + 0x40);
    VU0_LOAD_MATRIX_B(instance->matrix);
    sdfComposeVuMatrixFromRegisters();
    VU0_STORE_MATRIX(matrix);
    matrix[12] = ((BillObj *)instance->billboard)->unk0;
    matrix[13] = ((BillObj *)instance->billboard)->unk4;
    matrix[14] = ((BillObj *)instance->billboard)->unk08;
    VU0_LOAD_MATRIX(matrix);
    sdfConsAppendVuPacket(list, 0);
    memset(&params, 0, sizeof(params));
    params.primitive = 0x4000;
    params.parameters = D_0034E090;
    params.positions = (u128 *)positions;
    params.colors = D_0034E0A0;
    params.texcoords = (u32 *)uv;
    params.color = ((BillObj *)instance->billboard)->childParam;
    params.parameterCount = 2;
    params.vertexCount = 4;
    child = (BillChildPayload *)modeValues[1];
    x = child->x * ((BillObj *)instance->billboard)->childScaleX;
    y = child->y * ((BillObj *)instance->billboard)->childScaleY;
    width = child->halfWidth * ((BillObj *)instance->billboard)->childScaleX;
    height = child->halfHeight * ((BillObj *)instance->billboard)->childScaleY;
    cosine = sdfEvaluateCosineViaSinePhaseShift(((BillObj *)instance->billboard)->lengthScale);
    sine = sdfSinPoly(((BillObj *)instance->billboard)->lengthScale);
    positions[0][0] = (x - width) * cosine - (y - height) * sine;
    positions[0][1] = (x - width) * sine + (y - height) * cosine;
    positions[0][2] = 0.0f;
    positions[1][0] = (x + width) * cosine - (y - height) * sine;
    positions[1][1] = (x + width) * sine + (y - height) * cosine;
    positions[1][2] = 0.0f;
    positions[2][0] = (x - width) * cosine - (y + height) * sine;
    positions[2][1] = (x - width) * sine + (y + height) * cosine;
    positions[2][2] = 0.0f;
    positions[3][0] = (x + width) * cosine - (y + height) * sine;
    positions[3][1] = (x + width) * sine + (y + height) * cosine;
    positions[3][2] = 0.0f;
    texture = (SdfTex *)child->value;
    width = 1.0f / (f32)(texture->width << 4);
    height = 1.0f / (f32)(texture->height << 4);
    uv[0][0] = child->uv.components[0] * width;
    uv[0][1] = child->uv.components[1] * height;
    uv[1][0] = child->uv.components[2] * width;
    uv[1][1] = child->uv.components[3] * height;
    uv[2][0] = child->uv.components[6] * width;
    uv[2][1] = child->uv.components[7] * height;
    uv[3][0] = child->uv.components[4] * width;
    uv[3][1] = child->uv.components[5] * height;
    func_002DA438((SdfTextParam *)instance->resource, (u32)texture);
    switch ((u32)modeValues[0]) {
    case 2:
    case 3:
        child = (BillChildPayload *)modeValues[2];
        x = child->x * ((BillObj *)instance->billboard)->childScaleX;
        y = child->y * ((BillObj *)instance->billboard)->childScaleY;
        width = child->halfWidth * ((BillObj *)instance->billboard)->childScaleX;
        height = child->halfHeight * ((BillObj *)instance->billboard)->childScaleY;
        params.primitive |= 0x1000;
        params.extraTexcoords = (u32 *)secondaryUv;
        cosine = sdfEvaluateCosineViaSinePhaseShift(((BillObj *)instance->billboard)->lengthScale);
        sine = sdfSinPoly(((BillObj *)instance->billboard)->lengthScale);
        positions[0][0] = (x - width) * cosine - (y - height) * sine;
        positions[0][1] = (x - width) * sine + (y - height) * cosine;
        positions[0][2] = 0.0f;
        positions[1][0] = (x + width) * cosine - (y - height) * sine;
        positions[1][1] = (x + width) * sine + (y - height) * cosine;
        positions[1][2] = 0.0f;
        positions[2][0] = (x - width) * cosine - (y + height) * sine;
        positions[2][1] = (x - width) * sine + (y + height) * cosine;
        positions[2][2] = 0.0f;
        positions[3][0] = (x + width) * cosine - (y + height) * sine;
        positions[3][1] = (x + width) * sine + (y + height) * cosine;
        positions[3][2] = 0.0f;
        texture = (SdfTex *)child->value;
        width = (f32)(texture->width << 4);
        height = (f32)(texture->height << 4);
        secondaryUv[0][0] = child->uv.components[0] / width;
        secondaryUv[0][1] = child->uv.components[1] / height;
        secondaryUv[1][0] = child->uv.components[2] / width;
        secondaryUv[1][1] = child->uv.components[3] / height;
        secondaryUv[2][0] = child->uv.components[6] / width;
        secondaryUv[2][1] = child->uv.components[7] / height;
        secondaryUv[3][0] = child->uv.components[4] / width;
        secondaryUv[3][1] = child->uv.components[5] / height;
        func_002DA5E0((SdfTextParam *)instance->resource, (u32)texture);
        break;
    }
    sdfConsAppendAssetPacket(list, instance->resource, 0);
    sdfAppendPacket((SdfListHead *)list, (u32)func_0015FE20(&params));
    surface = D_0034E0B0[((BillObj *)instance->billboard)->unk2E];
    surface->append((SdfListHead *)surface, (SdfListHead *)list);
}
