typedef struct EffPacketParams {
    s16 parameterCount;
    s16 vertexCount;
    u16 primitive;
    u16 mask;
    u32 color;
    u32 *parameters;
    u128 *positions;
    u128 *normals;
    u32 *texcoords;
    u32 *extraTexcoords;
    u32 *colors;
    void *(*allocate)(s32);
    f32 depth;
} EffPacketParams;

typedef struct SdfTextParam SdfTextParam;
extern u32 D_003AA9C0[];
extern u32 D_003AA9D0[];
extern SdfPoolNode *D_003AA9E0[];
extern void sdfComposeVuMatrixFromRegisters(void);
extern void sdfConsAppendVuPacket(s32, s32 (*)(s32));
extern void sdfConsAppendAssetPacket(s32, void *, s32 (*)(s32));
extern void sdfAppendPacket(SdfListHead *, u32);
extern f32 sdfEvaluateCosineViaSinePhaseShift(f32);
extern f32 sdfSinPoly(f32);
extern void func_003332E8(SdfTextParam *, u32);
extern void func_00333490(SdfTextParam *, u32);
extern void *func_00167A10(EffPacketParams *);

void func_0015A4B0(EffInstance *instance) {
    EffPacketParams params;
    s32 modeValues[3];
    f32 matrix[4][4] __attribute__((aligned(16)));
    f32 positions[4][4] __attribute__((aligned(16)));
    f32 uv[4][2];
    f32 secondaryUv[4][2];
    s32 list;
    BillChildPayload *child;
    SdfTex *texture;
    SdfPoolNode *surface;
    f32 x, y;
    f32 scaleX, scaleY;
    f32 cornerX, cornerY;
    f32 cosine, sine;
    f32 width, height;

    if (!billGetKindOneParameter((BillObj *)instance->billboard)) {
        return;
    }
    effReadBillboardModeValues(instance, modeValues);
    list = sdfAllocPacketAligned(0x20);
    sdfInitPacketList((SdfListHead *)list);
    VU0_LOAD_MATRIX(instance->transform);
    VU0_LOAD_MATRIX_B(instance->localMatrix);
    sdfComposeVuMatrixFromRegisters();
    VU0_STORE_MATRIX_UNCLOBBERED(matrix);
    matrix[3][0] = ((BillObj *)instance->billboard)->unk0;
    matrix[3][1] = ((BillObj *)instance->billboard)->unk4;
    matrix[3][2] = ((BillObj *)instance->billboard)->unk08;
    VU0_LOAD_MATRIX(matrix);
    sdfConsAppendVuPacket(list, 0);
    memset(&params, 0, sizeof(params));
    params.primitive = 0x4000;
    params.parameters = D_003AA9C0;
    params.positions = (u128 *)positions;
    params.colors = D_003AA9D0;
    params.texcoords = (u32 *)uv;
    params.color = ((BillObj *)instance->billboard)->childParam;
    params.parameterCount = 2;
    params.vertexCount = 4;
    child = (BillChildPayload *)modeValues[1];
    scaleX = ((BillObj *)instance->billboard)->childScaleX;
    scaleY = ((BillObj *)instance->billboard)->childScaleY;
    x = child->x * scaleX;
    y = child->y * scaleY;
    width = child->halfWidth * scaleX;
    height = child->halfHeight * scaleY;
    cosine = sdfEvaluateCosineViaSinePhaseShift(((BillObj *)instance->billboard)->lengthScale);
    sine = sdfSinPoly(((BillObj *)instance->billboard)->lengthScale);
    cornerX = x - width;
    cornerY = y - height;
    positions[0][0] = cornerX * cosine - cornerY * sine;
    positions[0][1] = cornerX * sine + cornerY * cosine;
    positions[0][2] = 0.0f;
    cornerX = x + width;
    cornerY = y - height;
    positions[1][0] = cornerX * cosine - cornerY * sine;
    positions[1][1] = cornerX * sine + cornerY * cosine;
    positions[1][2] = 0.0f;
    cornerX = x + width;
    cornerY = y + height;
    positions[3][0] = cornerX * cosine - cornerY * sine;
    positions[3][1] = cornerX * sine + cornerY * cosine;
    positions[3][2] = 0.0f;
    cornerX = x - width;
    cornerY = y + height;
    positions[2][0] = cornerX * cosine - cornerY * sine;
    positions[2][1] = cornerX * sine + cornerY * cosine;
    positions[2][2] = 0.0f;
    texture = (SdfTex *)child->value;
    width = 1.0f / (f32)(texture->width * 16);
    height = 1.0f / (f32)(texture->height * 16);
    uv[0][0] = child->uv.components[0] * width;
    uv[0][1] = child->uv.components[1] * height;
    uv[1][0] = child->uv.components[2] * width;
    uv[1][1] = child->uv.components[3] * height;
    uv[2][0] = child->uv.components[6] * width;
    uv[2][1] = child->uv.components[7] * height;
    uv[3][0] = child->uv.components[4] * width;
    uv[3][1] = child->uv.components[5] * height;
    func_003332E8((SdfTextParam *)instance->renderState, (u32)texture);
    switch ((u32)modeValues[0]) {
    case 2:
    case 3:
        child = (BillChildPayload *)modeValues[2];
        scaleX = ((BillObj *)instance->billboard)->childScaleX;
        scaleY = ((BillObj *)instance->billboard)->childScaleY;
        x = child->x * scaleX;
        y = child->y * scaleY;
        width = child->halfWidth * scaleX;
        height = child->halfHeight * scaleY;
        params.primitive |= 0x1000;
        params.extraTexcoords = (u32 *)secondaryUv;
        cosine = sdfEvaluateCosineViaSinePhaseShift(((BillObj *)instance->billboard)->lengthScale);
        sine = sdfSinPoly(((BillObj *)instance->billboard)->lengthScale);
        cornerX = x - width;
        cornerY = y - height;
        positions[0][0] = cornerX * cosine - cornerY * sine;
        positions[0][1] = cornerX * sine + cornerY * cosine;
        positions[0][2] = 0.0f;
        cornerX = x + width;
        cornerY = y - height;
        positions[1][0] = cornerX * cosine - cornerY * sine;
        positions[1][1] = cornerX * sine + cornerY * cosine;
        positions[1][2] = 0.0f;
        cornerX = x + width;
        cornerY = y + height;
        positions[3][0] = cornerX * cosine - cornerY * sine;
        positions[3][1] = cornerX * sine + cornerY * cosine;
        positions[3][2] = 0.0f;
        cornerX = x - width;
        cornerY = y + height;
        positions[2][0] = cornerX * cosine - cornerY * sine;
        positions[2][1] = cornerX * sine + cornerY * cosine;
        positions[2][2] = 0.0f;
        texture = (SdfTex *)child->value;
        width = (f32)(texture->width * 16);
        height = (f32)(texture->height * 16);
        secondaryUv[0][0] = child->uv.components[0] / width;
        secondaryUv[0][1] = child->uv.components[1] / height;
        secondaryUv[1][0] = child->uv.components[2] / width;
        secondaryUv[1][1] = child->uv.components[3] / height;
        secondaryUv[2][0] = child->uv.components[6] / width;
        secondaryUv[2][1] = child->uv.components[7] / height;
        secondaryUv[3][0] = child->uv.components[4] / width;
        secondaryUv[3][1] = child->uv.components[5] / height;
        func_00333490((SdfTextParam *)instance->renderState, (u32)texture);
        break;
    }
    sdfConsAppendAssetPacket(list, instance->renderState, 0);
    sdfAppendPacket((SdfListHead *)list, (u32)func_00167A10(&params));
    surface = D_003AA9E0[((BillObj *)instance->billboard)->unk2E];
    surface->append((SdfListHead *)surface, (SdfListHead *)list);
}
